version: '3'
services:
  database:
    container_name: "mysql"
    restart: unless-stopped
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=employees
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST='%'
    ports:
      - 3306:3306
    volumes:
      - 'mysql:/var/lib/mysql'
      - './sample:/sample/sakila'
    labels:
      - "PRIORITY=0"
  adminer:
    container_name: "mysql-adminer"
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8306:8080
    depends_on:
      - database
volumes:
  mysql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/data/docker-volumes/mysql'