version: '3'
services:
  portainer:
    container_name: "portainer"
    restart: unless-stopped
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    labels:
      - "PRIORITY=0"
volumes:
  portainer:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/data/docker-volumes/portainer'